services:
  pubsub:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pubsub_service
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    restart: unless-stopped
